spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: sqlsrvr
    url: jdbc:postgresql://localhost:5432/db_pathfinder?currentSchema=pathfinder&ssl=false
    username: admin
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    activate:
      on-profile: dev

app:
  jwt:
    secret: jwtsecret
    expiraton-in-ms: 86400000
    internalAccessKey: internalaccesskey

mailgun:
  api:
    domain: sandbox130d5cbb623e4ed0bb38ef303c11bf59.mailgun.org
    key: 24576801540933b80795f0c65737fbc8-fb87af35-27aac0fb