spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: sqlsrvr
    url: jdbc:postgresql://localhost:5432/db_pathfinder?currentSchema=pathfinder&ssl=false
    username: admin
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  jwt:
    secret: TrustGodWithAllYourHeart
    expiraton-in-ms: 86400000