logging:
  level:
    .: error
    org.springframework: ERROR
    com.bkc: ERROR

spring:
  profiles: 
    active: "dev"

---

spring:
  profiles: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    password: pwd
    url: jdbc:postgresql://localhost:5432/db_db?currentSchema=cs&ssl=false
    username: user
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  jwt:
    secret: jwtsecret
    expiraton-in-ms: 86400000
    internalAccessKey: internalaccesskey
  
---

spring:
  profiles: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${DB_PASS}
    url: ${DB_URL}
    username: ${DB_USER}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  jwt:
    secret: ${JWT_SECRET}
    expiraton-in-ms: 86400000
    internalAccessKey: ${INTERNAL_API_KEY}