logging:
  level:
    .: error
    org.springframework: ERROR
    com.bkc: ERROR

spring:
  profiles: 
    active: "default"
  datasource:
    driver-class-name: org.postgresql.Driver
    password: pwd
    url: jdbc:postgresql://localhost:5432/db_db?currentSchema=cs&ssl=false
    username: user
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  jwt:
    secret: jwtsecret
    expiraton-in-ms: 86400000
    internalAccessKey: internalaccesskey