spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: sqlsrvr
    url: jdbc:postgresql://localhost:5432/db_pathfinder?currentSchema=pathfinder&ssl=false
    username: admin
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    activate:
      on-profile: dev

app:
  jwt:
    secret: jwtsecret
    expiraton-in-ms: 86400000
    internalAccessKey: internalaccesskey

mailgun:
  api:
    domain: sandboxaf701e6bbfba49e69a208f3aca952a0a.mailgun.org
    key: df2ed4c99f5f97120b528a958fc288b9-fb87af35-7520924f
    sender: bumkicho@gmail.com